[package]
edition = "2018"

name = "advent_2020"
version = "2020.12.11"

authors = ["Randy Eckenrode <randy@largeandhighquality.com>"]
description = "Advent of Code 2020 solutions written in Rust"

[dependencies]
"clap" = "3.0.0-beta.2"
